config/routes.rb
Rails.application.routes.draw do
  get    '/login'   => 'user_log#new'
  post   '/login'   => 'user_log#create'
  delete '/logout' => 'user_log#destroy'

  get '/site/top'
  root "site#top"
  resources :sub_objs
  resources :main_objs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main_obj.rb
class MainObj < ApplicationRecord
    belongs_to :user
end

app/models/sub_obj.rb
class SubObj < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :main_objs, dependent: :destroy
    has_many :sub_objs, dependent: :destroy
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UserLogHelper
end

app/controllers/main_objs_controller.rb
class MainObjsController < ApplicationController
  before_action :set_main_obj, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  
  def login
    if session[:user_id].blank?
      redirect_to login_path
      #user = User.create
      #session[:user_id] = user.id
    end
    @user_id = session[:user_id]
  end

  # GET /main_objs
  # GET /main_objs.json
  def index
    @main_objs = MainObj.all
  end

  # GET /main_objs/1
  # GET /main_objs/1.json
  def show
  end

  # GET /main_objs/new
  def new
    @main_obj = MainObj.new
  end

  # GET /main_objs/1/edit
  def edit
  end

  # POST /main_objs
  # POST /main_objs.json
  def create
    @main_obj = current_user.main_objs.new(main_obj_params)

    respond_to do |format|
      if @main_obj.save
        format.html { redirect_to @main_obj, notice: 'Main obj was successfully created.' }
        format.json { render :show, status: :created, location: @main_obj }
      else
        format.html { render :new }
        format.json { render json: @main_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_objs/1
  # PATCH/PUT /main_objs/1.json
  def update
    respond_to do |format|
      if @main_obj.update(main_obj_params)
        format.html { redirect_to @main_obj, notice: 'Main obj was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_obj }
      else
        format.html { render :edit }
        format.json { render json: @main_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_objs/1
  # DELETE /main_objs/1.json
  def destroy
    @main_obj.destroy
    respond_to do |format|
      format.html { redirect_to main_objs_url, notice: 'Main obj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_obj
      @main_obj = MainObj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_obj_params
      params.require(:main_obj).permit(:title, :text, :limit, :user_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def top
  end
end

app/controllers/sub_objs_controller.rb
class SubObjsController < ApplicationController
  before_action :set_sub_obj, only: [:show, :edit, :update, :destroy]
  before_action :login
  def login
    if session[:user_id].blank?
      redirect_to user_log_
      #user = User.create
      #session[:user_id] = user.id
    end
    @user_id = session[:user_id]
  end

  # GET /sub_objs
  # GET /sub_objs.json
  def index
    @sub_objs = SubObj.all
  end

  # GET /sub_objs/1
  # GET /sub_objs/1.json
  def show
  end

  # GET /sub_objs/new
  def new
    @sub_obj = SubObj.new
  end

  # GET /sub_objs/1/edit
  def edit
  end

  # POST /sub_objs
  # POST /sub_objs.json
  def create
    @sub_obj = current_user.sub_objs.new(sub_obj_params)

    respond_to do |format|
      if @sub_obj.save
        format.html { redirect_to main_obj_path(id: current_user.main_objs.ids), notice: 'Sub obj was successfully created.' }
        format.json { render template: "/main_objs/current_user" }
      else
        format.html { render template: "/main_objs/new" }
        format.json { render json: @sub_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_objs/1
  # PATCH/PUT /sub_objs/1.json
  def update
    respond_to do |format|
      if @sub_obj.update(sub_obj_params)
        format.html { redirect_to @main_obj, notice: 'Sub obj was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_obj }
      else
        format.html { render :edit }
        format.json { render json: @sub_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_objs/1
  # DELETE /sub_objs/1.json
  def destroy
    @sub_obj.destroy
    respond_to do |format|
      format.html { redirect_to sub_objs_url, notice: 'Sub obj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_obj
      @sub_obj = SubObj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_obj_params
      params.require(:sub_obj).permit(:title, :text, :limit, :main_obj_id)
    end
end

app/controllers/user_log_controller.rb
class UserLogController < ApplicationController
  def new
  end

  def create
    user = User.find_by(mail: params[:user_log][:mail].downcase)
    if user && user.authenticate(params[:user_log][:password])
      log_in user
      current_user
      if MainObj.find_by(user_id: @current_user.id )
        redirect_to main_obj_path, notice: 'ログインに成功しました'
      else
        redirect_to new_main_obj_path, notice: 'ログインに成功しました'
      end
    else
      render 'new', alert: 'ログインできませんでした'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    log_in @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_main_obj_path, notice: '登録完了しました' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        current_user
        format.html { redirect_to main_obj_path(id: MainObj.find_by(user_id: @current_user.id).id), notice: 'User was successfully updated.' }
        format.json { render template: "/main_objs/current_user" }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_objs_helper.rb
module MainObjsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sub_objs_helper.rb
module SubObjsHelper
end

app/helpers/user_log_helper.rb
module UserLogHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miracolo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset=utf8>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scable=no">
    <title>PETIET</title>
    <link href="css/test1.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</script>

  <body  style="background:#e6e6e6;">
    <% if flash[:notice] %>
      <div class="alert alert-success" style="position:absolute;">
        <%= notice %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main_objs/_form.html.erb
<!-- editもnewもこれを呼び出す。つまりgoal editの初回設定と変更のやつ -->
<%= form_for(main_obj) do |f| %>
  <% if main_obj.errors.any? %>
    <div id="error_explanation">
      <h2 ><%= pluralize(main_obj.errors.count, "error") %> prohibited this main_obj from being saved:</h2>

      <ul>
      <% main_obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-xs-2 col-md-2 col-lg-2"></div>

<div class="col-xs-7 col-md-7 col-lg-7" style="background-color: #e6e6e6;">
  <div class="col-xs-12 col-md-12 col-lg-12">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <div class="field " >
        <%= f.label :目標を決めましょう %>
        <%= f.text_field :title, :class => "col-xs-8 col-md-8 col-lg-8" %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-12 col-lg-12">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <div class="field " >
        <%= f.label :具体的にすることを書いてください。 %>
        <%= f.text_area :text, :class => "col-xs-10 col-md-10 col-lg-10" %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-12 col-lg-12">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <div class="field">
        <%= f.label "期限を決めましょう。" %>
        <%= f.datetime_select :start %>〜
      </div>
      <div class="field">〜
        <%= f.datetime_select :limit %>
      </div>
    </div>
    <div class="col-xs-12 col-md-12 col-lg-12" style="margin-top: 20px; margin-right: auto; margin-left: auto;">
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/main_objs/edit.html.erb
<!-- goal editの代わり　-->
<header>
    MIRACOLO
</header>
<h1 style="margin-left:50px;">目標編集</h1></h1>

<%= render 'form', main_obj: @main_obj %>

<div class="col-xs-3 col-md-3 col-lg-3">
  <div id="menu11" class="col-xs-12 col-md-12 col-lg-12"><%= link_to "Top", root_path %></div>
  <div id="menu12" class="col-xs-12 col-md-12 col-lg-12"><%= link_to 'User', edit_user_path(id: @current_user.id) %></div>
  <div id="menu13" class="col-xs-12 col-md-12 col-lg-12"><%= link_to 'Log Out', logout_path, method: :delete %></div>
</div>

app/views/main_objs/new.html.erb
<!-- これもgoal editやけど、初回の時の　-->
<%= link_to "MIRACOLO", root_path %>

<h1 style="margin-left:50px;">目標設定</h1>

<%= render 'form', main_obj: @main_obj %>

<div class="col-xs-3 col-md-3 col-lg-3">
  <div id="menu11" class="col-xs-12 col-md-12 col-lg-12"><%= link_to "Top", root_path %></div>
  <div id="menu12" class="col-xs-12 col-md-12 col-lg-12"><%= link_to 'User', edit_user_path(id: @current_user.id) %></div>
  <div id="menu13" class="col-xs-12 col-md-12 col-lg-12"><%= link_to 'Log Out', logout_path, method: :delete %></div>
</div>

app/views/main_objs/show.html.erb
<!-- test1ってなってた、メインのページ -->
<body  style="backgroud:#e6e6e6;">
<div class="row">
  <header class=" col-xm-12 col-md-12 col-lg-12 header">
 MIRACOLO
</header>
</div>
<div class="sidebar2">
  <div class="time"></div>
  <div class="line"></div>
</div>
  <div class="content">
  <div class="a" ></div>
  <div class="b" ></div>
  <div class="c" ></div>
  <div class="d" ></div>
  <div class="e" id="trigger-overlay" type="button"><br>
    <p class="e-1"><%= @main_obj.title %></p>
  </div>
  <div class="f" ></div>
  <div class="g" ></div>
  <div class="h" ></div>
  <div class="i" ></div>
</div>
<div class="sidebar">
  <div class="menu1"><%= link_to 'Edit', edit_main_obj_path(id: @main_obj.id %></div>
  <div class="menu2"><%= link_to 'User', edit_user_path %></div>
  <div class="menu3"><%= link_to 'Log Out', logout_path, method: :delete %></div>
</div>
<div class="overlay overlay-door way" style="background: #cccccc;">
  <button type="button" class="overlay-close">Close</button>
  <nav>
    <ul>
			<li>
        <p href="#" id="yume">
          <strong>Title:</strong>
          <%= @main_obj.title %>
        </p>
      </li>
			<li>
        <a href="#" class="detail">
          <strong>Text:</strong>
          <%= @main_obj.text %>
        </a>
      </li>
			<li>
        <p href="#" class="detail">
          <strong>Limit:</strong>
          <%= @main_obj.limit %>
        </p>
      </li>
		</ul>
	</nav>
</div>

<script src="js/classie.js"></script>
<script src="js/demo1.js"></script>
</body>
<!--

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @main_obj.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @main_obj.text %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @main_obj.limit %>
</p>

<p>
  <strong>User:</strong>
  <%= @main_obj.user_id %>
</p>

<%= link_to 'Edit', edit_main_obj_path(@main_obj) %> |
<%= link_to 'Back', main_objs_path %>
-->

app/views/site/top.html.erb
<!-- これはtop -->
<body style="background-color:#e6e6e6;">
  <div class="header">
    <div class="row">
      <div class="col-xs-12 col-md-12 col-lg-12 head"><%= image_tag 'logo.png',:style=>"height:60px; width:60px; margin-top:-10px;"%> MiRACOLO </div>
      <div class="col-xs-6 col-md-3 col-lg-3 login"><%= link_to "Log in", login_path,:style=>"color:white;"%></div>
      <div class="col-xs-6 col-md-3 col-lg-3 signup"><%= link_to "Sign up", new_user_path,:style=>"color:white;" %></div>
      <div class="col-xs-6 col-md-3 col-lg-3 about"><a href="#abou" style="color:white;"> About</a></div>
      <div class="col-xs-6 col-md-3 col-lg-3 producer"><a href="#produce" style="color:white;"> Producer</a></div> 
      <div class=" col-xs-12 col-md-12 col-lg-12  " style="background-color: #1b1464; height:600px;">
        <h1 class="mozi "><a href="" style="color:white;">Dream is come true. </a> </h1>
        <h2 class="mozi2 ">It's not destiny, but Miracle!</h2>
      </div>
    </div> 
  </div>

<div class="row">
   <div class="col-xs-12 col-md-12 col-lg-12 " >
  <h1 class="mozi3-1" style="color: #1b1464;" id="abou">ABOUT</h1>
  </div>
    <div class="col-xs-12 col-md-12 col-lg-12 " >
      <div class="col-xs-12 col-md-4 col-lg-4"> 
        <div class="col-xs-12 col-md-12 col-lg-12 about1" >
          <h2 class="mozi3 ">What is Miracolo?</h2>
          <p class="mozi3-3 ">MIRACOLOとは、あなたの夢をサポートするツールです。Miracoloはあなたの夢をサポートします。</p>
        </div>
      </div>
      <div class="col-xs-12 col-md-4 col-lg-4 ">
        <div class="col-xs-12 col-md-12 col-lg-12 about2">
          <h2 class="mozi3 ">Who uses Miracolo?</h2>
          <p class="mozi3-3 ">誰が使うかって？それは、夢を持つ人全員ですよ。あなたにも叶えたい夢はないですか？</p>
        </div>
      </div>
      <div class="col-xs-12 col-md-4 col-lg-4 ">
        <div class="col-xs-12 col-md-12 col-lg-12 about3" >
          <h2 class="mozi3 ">How to use Miracolo</h2>
          <p class="mozi3-3 ">あなたの夢に応じた目標と期限を設定するだけでOK 。もし期限が難しいなと思ったら変更もできます。サボるために使わないように要注意。</p>
        </div>
      </div>
         <div class="col-xs-12 col-md-12 col-lg-12 " >
         <h1 class="mozi3-2" style="color: #1b1464;" id="produce">PRODUCER</h1>
         </div>
    <div class="col-xs-12 col-md-12 col-lg-12 "style="height:500px" >
      <div class="col-xs-12 col-md-4 col-lg-4"> 
        <div class="col-xs-12 col-md-12 col-lg-12 about1" >
          <h2 class="mozi3 ">ジャスティンビーバー</h2>
          <p class="mozi3-3 ">MIRACOLOとは、あなたの夢をサポートするツールです。Miracoloはあなたの夢をサポートします。</p>
        </div>
      </div>
      <div class="col-xs-12 col-md-4 col-lg-4 ">
      <div class="col-xs-12 col-md-12 col-lg-12 about2">
        <h2 class="mozi3 ">イニエスタ</h2>
        <p class="mozi3-3 ">誰が使うかって？それは、夢を持つ人全員ですよ。あなたにも叶えたい夢はないですか？</p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-4 ">
      <div class="col-xs-12 col-md-12 col-lg-12 about3" >
        <h2 class="mozi3 ">ジョニーデップ</h2>
        <p class="mozi3-3 ">あなたの夢に応じた目標と期限を設定するだけでOK 。もし期限が難しいなと思ったら変更もできます。サボるために使わないように要注意。</p>
      </div>
    </div>
    </div>
  </div>

</div>

app/views/sub_objs/_form.html.erb
<!-- main_objの_formと一緒。editもnewもこれを呼び出す。つまりgoal editの初回設定と変更のやつ -->
<%= form_for(sub_obj) do |f| %>
  <% if sub_obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_obj.errors.count, "error") %> prohibited this sub_obj from being saved:</h2>

      <ul>
      <% sub_obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field ">
    <%= f.label :目標を決めましょう %>
    <%= f.text_field :title,:size => '40*40' %>
  </div>

  <div class="field ">
    <%= f.label :具体的にすることを書いてください。 %>
    <%= f.text_area :text, :size => '70*40' %>
  </div>
 
  <div class="field">
    <%= f.label :期限を決めましょう。 %>
    <%= f.datetime_select :start %>〜
  </div>

   <div class="field">〜
    <%= f.datetime_select :limit %>
  </div>

  <div class="actions">
    <%= f.submit 'GO'%>
  </div>
<% end %>

app/views/sub_objs/edit.html.erb
<!-- goal editの代わり　-->
<h1>目標編集</h1>

<%= render 'form', sub_obj: @sub_obj %>

<%= link_to 'Show', @sub_obj %> |
<%= link_to 'Back', sub_objs_path %>

app/views/sub_objs/new.html.erb
<!-- これもgoal editやけど、初回の時の　-->

<header>
MIRACOLO
</header>
<h1 style="margin-left:50px;">New Goal</h1>
<%= render 'form', sub_obj: @sub_obj %>
<div class="actions">
<%= link_to 'Back', sub_objs_path %>
</div>

app/views/user_log/new.html.erb
<!-- user_log関係ややこしいねんけど、要はuserの登録変更削除(sign up, edit, delete)をuserがやってて、
user_logはログインログアウト(sigi in, sign out)を記録する役割。
やからuser_logにはログイン画面用のビューだけ-->
<div class="row">
<header class="header col-xs-12 col-sm-12 col-md-12 col-lg-12">
       <%= link_to "MIRACOLO", root_path,:style =>"color:#e6e6e6;" %>
</header>
</div>

<%= form_for(:user_log, url: login_path) do |f| %>
    <h1  class="col-xs-12 col-sm-12 col-md-12 col-lg-12">ログイン</h1>
    
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
      <div class="col-xs-12 col-sm-12  col-md-12 col-lg-12" style="text-align:center;">
        <!--<%= f.label :name, "image"%>--></br>
    <div class="image2"></div>
    </div>

      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="field2">
      <%= f.label :mail, 'メールアドレス' %></br>
      <%= f.text_field :mail %>
    </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="field2">
      <%= f.label :password, 'パスワード' %></br>
      <%= f.password_field :password %>
    </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="field2">
    <%= f.submit 'ログインする' %>
    </div>
    </div>
  </div>
<% end %>
<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
<div  id="menu3"class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><%= link_to "Sign Up", new_user_path %></div>
<div id="menu4" class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><%= link_to "Top", root_path %></div>
</div>
<!-- 元のコード
<!DOCTYPE html>
<html>
  <html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap </title>
    <link href="css/test1.css" rel="stylesheet">
    <script src="js/miracolo.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
      // 画面幅800px基準でzoomをセット
      $("html").css("zoom", $(window).width() / 1366);
      $(window).bind({
        "resize load orientationchange" : function(event) {
          var zoom = $(window).width() / 1366;
          $("html").css("zoom", zoom);
        }
      });
      $(function () {
        // ページ遷移
        $('#menu9').click(function() {
          window.location.href = 'signup.html';
          // target="_top"
          // top.location.href = '/';
        });
      });
      $(function () {
        // ページ遷移
        $('#menu10').click(function() {
          window.location.href = 'top.html';
          // target="_top"
          // top.location.href = '/';
        });
      });
    </script>
  </head>

  <body style="background-color:#e6e6e6">
    <header>
      MIRACOLO
    </header>
    
    <div class="content">
      <h1>Log In</h1>
    <div class="image"></div>
    <div class="field">
      Email<br>
      <textarea class="name" type="email"></textarea>
    </div>
    <div class="field">
      Password<br>
      <textarea class="name" type="password"></textarea>
    </div>
    <button class="button">登録</button>
  </div>
  <div class="sidebar">
    <div id="menu9">Sign up</div>
    <div id="menu10">Top</div>
  </div>
</body>
</html>　~もうどこで閉じてるかわからん・・・~
-->

app/views/users/edit.html.erb
<!-- 変更の時のページ -->
<div class="row">
<header class="header col-xs-12 col-sm-12 col-md-12 col-lg-12">
     <%= link_to "MIRACOLO", root_path,:style =>"color:#e6e6e6;" %>
</header>
</div>
<h1  class=" col-xs-12 col-sm-12 col-md-12 col-lg-12">ユーザー編集</h1>
<div class="row">
  <header class="header col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <%= link_to "MIRACOLO", root_path,:style =>"color:#e6e6e6;" %>
  </header>
  <h1 style="margin-left:70px;" class=" col-xs-12 col-sm-12 col-md-12 col-lg-12">ユーザー編集</h1>
</div>
<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
<%= render 'form', user: @user %>
</div>
<!--
<div class="field">
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>-->
<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
  <div  class="col-xs-12 col-md-12 col-sm-12 col-lg-12" id="menu1"><%= link_to "Top", root_path %></div>
  <div  class="col-xs-12 col-md-12 col-sm-12 col-lg-12" id="menu2"><%= link_to "Log in", login_path %></div>
</div>